//@version=5
strategy("Range Trading SOL/USD", overlay=true, pyramiding=3)

//English: Use this Strategy on the 1H Chart on Solana, only use it when the Market is Ranging! 
//German: Dieser Version der Strategie ist für den 1H chart auf Solana optimiert.


//Settings:
//100.000USD, 10% Margin, 15.000USD Position Size, 1H Chart on solana, 1 Year Test-time, 0.025% provision
//offsetlong=7, offsetshort=5
//Max. Loss = 7USD (avg. Prize diff.), lookback=72h

// Lookback Period
length = input.int(72, "Lookback")

// VAH / VAL approximation
high1 = ta.highest(high[12], length)
low1 = ta.lowest(low[12], length)

// Graphik
plot(high1, color=color.red, title="VAH")
plot(low1, color=color.green, title="VAL")

// Settings for absolute high/low
offsetlong = input.float(9, "offsetlong")
offsetshort = input.float(12, "offsetshort")

// Calculation of absoluten highs/lows
float absHigh = high1 + offsetlong
float absLow = low1 - offsetshort

// Graphik
plot(absHigh, color=color.rgb(221, 23, 195), title="absHigh")
plot(absLow, color=color.rgb(18, 57, 233), title="absLow")

// Entry conditions
shortCondition = ta.crossunder(close, high1)
longCondition = ta.crossover(close, low1)
// Entry execution
if shortCondition
    strategy.entry("Short", strategy.short)

if longCondition
    strategy.entry("Long", strategy.long)

// Exit conditions
if high > high1
    strategy.close("Long")

if low < low1
    strategy.close("Short")


// Risk Managment 
if high > absHigh
    strategy.close("Short")

if low < absLow
    strategy.close("Long")

// Risk Managment if code fails
maxLoss = input.float(7, "Max Verlust pro Trade")

currentLoss = strategy.position_size > 0 ? strategy.position_avg_price - close : close - strategy.position_avg_price

if currentLoss > maxLoss
    strategy.close_all()
