//@version=6 
strategy("Supertrend+atr", 
     overlay=true, 
     initial_capital=1000, 
     default_qty_type=strategy.cash,
     commission_type=strategy.commission.percent,
     commission_value=0.05)

Periods      = input.int(10, "ATR Period") // Période de l'ATR
Multiplier   = input.float(3.0, "ATR Multiplier", step=0.1)
changeATR    = input.bool(true, "Use built-in ATR?")
riskPerc     = input.float(5.0, "Risk per trade (%)", step=0.1)
leverage     = input.float(4.0, "Leverage", step=0.1)
trailMult    = input.float(1.5, "Trailing Stop ATR Mult", step=0.1)

atrLength    = input.int(14, "ATR Length pour Filtre")
atrMult      = input.float(0.5, "ATR Multiplier pour Filtre")
smaAtrLength = input.int(20, "SMA ATR Length") // Longueur de la moyenne mobile de l'ATR
atrFilter    = ta.atr(Periods) < ta.sma(ta.atr(atrLength), smaAtrLength) * atrMult // Filtre de consolidation basé sur l'ATR

atr_custom = ta.sma(ta.tr, Periods)
atr_val = changeATR ? ta.atr(Periods) : atr_custom

src = hl2

up = src - (Multiplier * atr_val)
up1 = nz(up[1], up)
up := close[1] > up1 ? math.max(up, up1) : up

dn = src + (Multiplier * atr_val)
dn1 = nz(dn[1], dn)
dn := close[1] < dn1 ? math.min(dn, dn1) : dn

trend = 1
trend := nz(trend[1], trend)
trend := trend == -1 and close > dn1 ? 1 : trend == 1 and close < up1 ? -1 : trend

buySignal  = trend == 1 and trend[1] == -1
sellSignal = trend == -1 and trend[1] == 1

capital = strategy.equity
riskAmount = capital * (riskPerc / 100)

stopDist = math.max(atr_val * Multiplier, syminfo.mintick)

rawSize = riskAmount / stopDist

leveragedSize = rawSize * leverage

posSize = math.max(0.0, leveragedSize)
posSize := math.min(posSize, 1e9)

canTrade = posSize > 0 and not na(posSize) and not atrFilter // Condition de non-trading pendant la consolidation

trail_offset = atr_val * trailMult


if (buySignal and canTrade)
    strategy.close("Short")  // ferme short = TP logique
    strategy.entry("Long", strategy.long, qty=posSize)
    strategy.exit("Long Exit",
         from_entry="Long",
         trail_offset=trail_offset,
         trail_points=trail_offset)

if (sellSignal and canTrade)
    strategy.close("Long")  // ferme long = TP logique
    strategy.entry("Short", strategy.short, qty=posSize)
    strategy.exit("Short Exit",
         from_entry="Short",
         trail_offset=trail_offset,
         trail_points=trail_offset)

plot(trend == 1 ? up : na, "Up Trend", color=color.green, linewidth=2)
plot(trend == -1 ? dn : na, "Down Trend", color=color.red, linewidth=2)

plotshape(buySignal, title="Buy", location=location.belowbar, 
     color=color.green, style=shape.labelup, text="BUY")

plotshape(sellSignal, title="Sell", location=location.abovebar, 
     color=color.red, style=shape.labeldown, text="SELL")