//@version=6
indicator(title="High Low Thach Fr", shorttitle="H/L Thach 2.0", overlay=true, max_lines_count=10)

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// DONCHIAN CHANNELS
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

length = input.int(20, minval=1, title="Donchian Length")
offset = input.int(0, "Offset")

lower = ta.lowest(length)
upper = ta.highest(length)
basis = math.avg(upper, lower)

plot(basis, "Basis", color=color.rgb(242, 54, 69, 50), offset=offset)

u = plot(upper, "Upper", color=color.rgb(41, 98, 255, 60), offset=offset)
l = plot(lower, "Lower", color=color.rgb(41, 98, 255, 60), offset=offset)

fill(u, l, color=color.rgb(33, 150, 243, 95), title="Background")

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ICHIMOKU - CÁC ĐƯỜNG CƠ BẢN
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

conversionPeriods = input.int(65, minval=1, title="Conversion Line Length")
basePeriods = input.int(129, minval=1, title="Base Line Length")
displacement = input.int(26, minval=1, title="Lagging Span")

donchian(len) =>math.avg(ta.lowest(len), ta.highest(len))

conversionLine = donchian(conversionPeriods)
baseLine = donchian(basePeriods)
leadLine1 = math.avg(conversionLine, baseLine)

plot(conversionLine, color=color.rgb(245, 124, 0), title="Conversion Line")
plot(baseLine, color=#9c27b0, title="Base Line")
plot(close, offset=-displacement + 1, color=color.rgb(128, 128, 128, 60), title="Lagging Span")

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CÁC MỐC NẾN
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

int candle199 = 199
int candle128 = 128
int candle64 = 64
int candle51 = 51
int candle25 = 25
int candle16 = 16
int candle8 = 8

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// HIỂN THỊ CÁC MỐC
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

showCandleLines = input.bool(true, "Hiển thị đường mốc nến")
showLabels = input.bool(true, "Hiển thị nhãn mốc nến")

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// MÀU ĐƯỜNG MỐC
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

color color199 = input.color(
     color.rgb(29, 210, 104, 80),
     "Màu nến 200"
     )

color color128 = input.color(
     color.rgb(29, 210, 104, 80),
     "Màu nến 129"
     )

color color64 = input.color(
     color.rgb(29, 210, 104, 80),
     "Màu nến 65"
     )

color color51 = input.color(
     color.rgb(29, 210, 104, 80),
     "Màu nến 52"
     )

color color25 = input.color(
     color.rgb(29, 210, 104, 80),
     "Màu nến 26"
     )

color color16 = input.color(
     color.rgb(29, 210, 104, 80),
     "Màu nến 17"
     )

color color8 = input.color(
     color.rgb(29, 210, 104, 80),
     "Màu nến 9"
     )

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// MÀU NHÃN
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

color color199t = color.rgb(29, 210, 104, 80)
color color128t = color.rgb(29, 210, 104, 80)
color color64t = color.rgb(29, 210, 104, 80)
color color51t = color.rgb(29, 210, 104, 80)
color color25t = color.rgb(29, 210, 104, 80)
color color16t = color.rgb(29, 210, 104, 80)
color color8t = color.rgb(29, 210, 104, 80)

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// XÁC ĐỊNH VỊ TRÍ CÁC NẾN
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

bool is199 = bar_index == last_bar_index - candle199
bool is128 = bar_index == last_bar_index - candle128
bool is64 = bar_index == last_bar_index - candle64
bool is51 = bar_index == last_bar_index - candle51
bool is25 = bar_index == last_bar_index - candle25
bool is16 = bar_index == last_bar_index - candle16
bool is8 = bar_index == last_bar_index - candle8

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// VẼ ĐƯỜNG THẲNG ĐỨNG
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

if showCandleLines and is199
    line.new(
         bar_index,
         low,
         bar_index,
         high,
         xloc=xloc.bar_index,
         extend=extend.both,
         color=color199,
         width=2
         )

if showCandleLines and is128
    line.new(
         bar_index,
         low,
         bar_index,
         high,
         xloc=xloc.bar_index,
         extend=extend.both,
         color=color128,
         width=2
         )

if showCandleLines and is64
    line.new(
         bar_index,
         low,
         bar_index,
         high,
         xloc=xloc.bar_index,
         extend=extend.both,
         color=color64,
         width=2
         )

if showCandleLines and is51
    line.new(
         bar_index,
         low,
         bar_index,
         high,
         xloc=xloc.bar_index,
         extend=extend.both,
         color=color51,
         width=2
         )

if showCandleLines and is25
    line.new(
         bar_index,
         low,
         bar_index,
         high,
         xloc=xloc.bar_index,
         extend=extend.both,
         color=color25,
         width=2
         )

if showCandleLines and is16
    line.new(
         bar_index,
         low,
         bar_index,
         high,
         xloc=xloc.bar_index,
         extend=extend.both,
         color=color16,
         width=2
         )

if showCandleLines and is8
    line.new(
         bar_index,
         low,
         bar_index,
         high,
         xloc=xloc.bar_index,
         extend=extend.both,
         color=color8,
         width=2
         )

//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// NHÃN MỐC NẾN
//━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

plotshape(
     showLabels and is199,
     title="Nến 200",
     style=shape.labeldown,
     location=location.abovebar,
     color=color199t,
     text="200",
     textcolor=color.black,
     size=size.small
     )

plotshape(
     showLabels and is128,
     title="Nến 129",
     style=shape.labeldown,
     location=location.abovebar,
     color=color128t,
     text="129",
     textcolor=color.black,
     size=size.small
     )

plotshape(
     showLabels and is64,
     title="Nến 65",
     style=shape.labeldown,
     location=location.abovebar,
     color=color64t,
     text="65",
     textcolor=color.black,
     size=size.small
     )

plotshape(
     showLabels and is51,
     title="Nến 52",
     style=shape.labeldown,
     location=location.abovebar,
     color=color51t,
     text="52",
     textcolor=color.black,
     size=size.small
     )

plotshape(
     showLabels and is25,
     title="Nến 26",
     style=shape.labeldown,
     location=location.abovebar,
     color=color25t,
     text="26",
     textcolor=color.black,
     size=size.small
     )

plotshape(
     showLabels and is16,
     title="Nến 17",
     style=shape.labeldown,
     location=location.abovebar,
     color=color16t,
     text="17",
     textcolor=color.black,
     size=size.small
     )

plotshape(
     showLabels and is8,
     title="Nến 9",
     style=shape.labeldown,
     location=location.abovebar,
     color=color8t,
     text="9",
     textcolor=color.black,
     size=size.small
     )
// Tooltips
string TT_AT = "If selected, the indicator automatically chooses the timeframe of the displayed bars. The chosen higher"
 + " timeframe is:\n\n"
 + " • '2 hours' if the chart timeframe is a seconds-based timeframe.\n"
 + " • '1 day' if the chart timeframe is lower than one day and not a seconds-based timeframe.\n"
 + " • '1 week' if the chart timeframe is higher than one day and lower than one week.\n"
 + " • '1 month' if the chart timeframe is higher than one week and lower than one month.\n"
 + " • '3 months' if the chart timeframe is higher than one month and lower than three months.\n"
 + " • '12 months' if the chart timeframe is higher than three months."
 + " \n\nIf not selected, it uses the timeframe specified in the 'Timeframe' input."
    
string TT_UC = "When this option is unchecked, MTPC will use intraday data while calculating on intraday charts."
 + " If Extended Hours are displayed on the chart, they will be taken into account during the calculation."
 + " If intraday OHLC values are different from daily-based values (normal for stocks), the MTPC will also differ."

// Color constants
color UP_COLOR   = color.rgb(0, 150, 136, 80)
color DN_COLOR   = color.rgb(244, 67, 54, 80)
color UPBD_COLOR = color.new(UP_COLOR, 90)
color DNBD_COLOR = color.new(DN_COLOR, 90)

//@enum An enumeration of named values representing display modes.
enum CalcType
    hl   = "High/Low Range"
    oc   = "Open/Close Range"
    ohlc = "OHLC"
    tr   = "True Range"

// Inputs
bool     autoTFInput        = input(true,             "Auto-timeframe", tooltip = TT_AT)
string   tfInput            = input.timeframe("1M",   "Timeframe", active = not autoTFInput)
CalcType calcTypeInput      = input.enum(CalcType.hl, "Calculation")
bool     useHaInput         = input.bool(false,       "Display Heikin Ashi values")
bool     useDailyInput      = input.bool(false,       "Use daily-based values", tooltip = TT_UC)

string   GRP01              = "Border and fill colors"
color    upBorderColorInput = input(UP_COLOR,       "Up bars  ", inline = "10", group = GRP01)
color    upBodyColorInput   = input(UPBD_COLOR,         "",      inline = "10", group = GRP01)
color    dnBorderColorInput = input(DN_COLOR,       "Down bars", inline = "11", group = GRP01)
color    dnBodyColorInput   = input(DNBD_COLOR,         "",      inline = "11", group = GRP01)

// @type A custom type for storing HTF bar information.
type OHLC
    float o
    float h
    float l
    float c
    float prevC

// @function Sets the position and colors of a box based on direction, or hides the box if `cond` is `true`. 
method setBox(box bx, cond, left, right, top, bottom, diff, upBodyColor, dnBodyColor, upBorderColor, dnBorderColor) =>
    color bodyColor   = diff < 0 ? dnBodyColor   : upBodyColor
    color borderColor = diff < 0 ? dnBorderColor : upBorderColor
    switch 
        cond => bx.set_bgcolor(na), bx.set_border_color(na)
        => 
            bx.set_left(left), bx.set_right(right)
            bx.set_top(top),   bx.set_bottom(bottom)
            bx.set_bgcolor(bodyColor), bx.set_border_color(borderColor)

// @function Returns a default higher-timeframe string based on the current chart's timeframe. 
selectAutoTimeframe() =>
    int secondsInTF = timeframe.in_seconds()
    string result = switch
        timeframe.isseconds   => "120"
        secondsInTF < 86400   => "1440"
        secondsInTF < 604800  => "1W"
        secondsInTF < 2628003 => "1M"
        secondsInTF < 7884009 => "3M"
        => "12M"

// @function Returns an adjusted timeframe, converting "1D" to "1440" during extended sessions.
selectTimeframeFromInput(tf) =>
    syminfo.session == session.extended and tf == "1D" ? "1440" : tf 

// @function Creates an `OHLC` object containing past bar prices.
makeOHLC(offset = 0) =>
    OHLC.new(open[offset], high[offset], low[offset], close[offset], close[offset + 1])

// @function Calculate Heikin Ashi values from standard OHLC values and previous HA open and close values. 
haFrom(o, h, l, c, prevHO, prevHC) =>
    float haC = (o + h + l + c) / 4
    float haO = na(prevHO) or na(prevHC) ? (o + c) / 2 : (prevHO + prevHC) / 2
    float haH = math.max(h, haO, haC)
    float haL = math.min(l, haO, haC)
    [haO, haH, haL, haC]

// @function Creates an `OHLC` object containing HTF values based on chart prices, with optional Heikin Ashi conversion. 
chartOHLC(tf, useHA) =>
    var float htfOpen   = na 
    var float htfHigh   = na 
    var float htfLow    = na 
    var float prevClose = na
    var float haClose   = na
    var float haOpen    = na
    var float prevHaC   = na
    var float prevHaO   = na
    if timeframe.change(tf)
        htfOpen   := open
        htfHigh   := high
        htfLow    := low
        prevClose := close[1]
        prevHaO   := haOpen
        prevHaC   := haClose
    htfHigh := math.max(high, htfHigh)
    htfLow  := math.min(low,  htfLow)
    switch 
        useHA => 
            [haO, haH, haL, haC] = haFrom(htfOpen, htfHigh, htfLow , close, prevHaO, prevHaC)
            haOpen  := haO
            haClose := haC
            OHLC.new(haO, haH, haL, haC, prevHaC)
        => OHLC.new(htfOpen, htfHigh, htfLow, close, prevClose)

//@variable The leftmost bar index for the box.
var int prevBarIndex = bar_index

// Determine the higher timeframe to use, and select the ticker (Heikin Ashi or regular).
var string timeframe = autoTFInput ? selectAutoTimeframe() : selectTimeframeFromInput(tfInput)
var string ticker    = useHaInput  ? ticker.heikinashi(syminfo.tickerid) : syminfo.tickerid

// Get HTF bar data using either chart-based aggregation or context requests. 
[bar0, bar1] = switch 
    not useDailyInput => [chartOHLC(timeframe, useHaInput), chartOHLC(timeframe, useHaInput)[1]]
    => request.security(ticker, timeframe, [makeOHLC(0), makeOHLC(1)], lookahead = barmerge.lookahead_on)

// Determine HTF bar coordinates based on the selected calculation mode.
bool isNewPeriod = timeframe.change(timeframe)
bool drawCurrent = barstate.islast and not isNewPeriod
OHLC bar = drawCurrent ? bar0 : bar1
bar := na(bar) ? OHLC.new() : bar
float diff  = bar.c - bar.o
int   left  = prevBarIndex
int   right = drawCurrent ? bar_index : bar_index - 1
[top, bottom] = switch calcTypeInput
    CalcType.oc => [bar.c, bar.o]
    CalcType.tr => [math.max(bar.h, bar.prevC), math.min(bar.l, bar.prevC)]
    =>             [bar.h, bar.l]

// On each new HTF bar, update the index and draw the finalized boxes.
if isNewPeriod
    prevBarIndex := bar_index
    box htBar = box.new(na, na, na, na)
    htBar.setBox(
         false, left, right, top, bottom, diff, upBodyColorInput, dnBodyColorInput, upBorderColorInput, 
         dnBorderColorInput
     )
    // Draw body open-close range if OHLC mode is enabled. 
    if calcTypeInput == CalcType.ohlc
        box htBody = box.new(na, na, na, na)
        htBody.setBox(
             false, left, right, bar.o, bar.c, diff, upBodyColorInput, dnBodyColorInput, upBorderColorInput, 
             dnBorderColorInput
         )

// For the current realtime HTF bar, draw the developing box. 
if barstate.islast
    var box rtBox = box.new(na, na, na, na)
    rtBox.setBox(
         isNewPeriod, left, right, top, bottom, diff, upBodyColorInput, dnBodyColorInput, upBorderColorInput,
         dnBorderColorInput
     )
    // Draw body open-close if OHLC mode is enabled. 
    if calcTypeInput == CalcType.ohlc
        var box rtBody = box.new(na, na, na, na)
        rtBody.setBox(
             isNewPeriod, left, right, bar.o, bar.c, diff, upBodyColorInput, dnBodyColorInput, upBorderColorInput,
             dnBorderColorInput
         )