//@version=6
indicator("BODY RANGE IN L-N OVERLAP", overlay=true)
candle_range = close >= open ? (close - open) : (open - close)
plot(candle_range, title="Candle Range", color=color.blue, style=plot.style_columns)

var color bullColor = input(title="Bull Color", defval=#26a69a, display=display.none)
var color bearColor = input(title="Bear Color", defval=#ef5350, display=display.none)
candleColor = close >= open ? bullColor : bearColor

plotcandle(
	 open,
	 high,
	 low,
	 close,
	 title="",
	 color=candleColor,
	 bordercolor=candleColor,
	 wickcolor=candleColor
     )
	 
plotshape(false, title="", text="", display=display.none)

string tradingSession = input.session("2000-2359", "Trading Session")
string sessionTimezone = "GMT+8"

bool inSession = not na(
     time(timeframe.period, tradingSession, sessionTimezone)
)

bgcolor(
     inSession
     ? color.new(color.blue, 92)
     : na
)